# coding: utf-8

"""
    LOCKSS Poller Service REST API

    API of the LOCKSS Poller REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_poller
from lockss_poller.api.poller_polls_api import PollerPollsApi  # noqa: E501
from lockss_poller.rest import ApiException


class TestPollerPollsApi(unittest.TestCase):
    """PollerPollsApi unit test stubs"""

    def setUp(self):
        self.api = lockss_poller.api.poller_polls_api.PollerPollsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_poller_poll_details(self):
        """Test case for get_poller_poll_details

        PollerDetails  # noqa: E501
        """
        pass

    def test_get_polls_as_poller(self):
        """Test case for get_polls_as_poller

        Get the list of recent polls as poller.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
