# coding: utf-8

"""
    LOCKSS Poller Service REST API

    API of the LOCKSS Poller REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_poller
from lockss_poller.api.voter_polls_api import VoterPollsApi  # noqa: E501
from lockss_poller.rest import ApiException


class TestVoterPollsApi(unittest.TestCase):
    """VoterPollsApi unit test stubs"""

    def setUp(self):
        self.api = lockss_poller.api.voter_polls_api.VoterPollsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_polls_as_voter(self):
        """Test case for get_polls_as_voter

        Get the list of recent voter only polls.  # noqa: E501
        """
        pass

    def test_get_voter_poll_details(self):
        """Test case for get_voter_poll_details

        VoterDetails  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
