# coding: utf-8

"""
    LOCKSS Poller Service REST API

    API of the LOCKSS Poller REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_poller
from lockss_poller.lockss-poller-python.cached_uri_set_spec import CachedUriSetSpec  # noqa: E501
from lockss_poller.rest import ApiException


class TestCachedUriSetSpec(unittest.TestCase):
    """CachedUriSetSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCachedUriSetSpec(self):
        """Test CachedUriSetSpec"""
        # FIXME: construct object with mandatory attributes with example values
        # model = lockss_poller.models.cached_uri_set_spec.CachedUriSetSpec()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
