# coding: utf-8

"""
    LOCKSS Poller Service REST API

    API of the LOCKSS Poller REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import lockss_poller
from lockss_poller.api.service_api import ServiceApi  # noqa: E501
from lockss_poller.rest import ApiException


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self):
        self.api = lockss_poller.api.service_api.ServiceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_call_poll(self):
        """Test case for call_poll

        Send a request to call a poll to the poller  # noqa: E501
        """
        pass

    def test_cancel_poll(self):
        """Test case for cancel_poll

        Stop a poll and remove from queue.  # noqa: E501
        """
        pass

    def test_get_poll_status(self):
        """Test case for get_poll_status

        Get queued poll status  # noqa: E501
        """
        pass

    def test_get_status(self):
        """Test case for get_status

        Get the status of the service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
