# coding: utf-8

"""
    LOCKSS Poller Service REST API

    API of the LOCKSS Poller REST Service  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: lockss-support@lockss.org
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "lockss-poller-python"
VERSION = "1.0.0"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="LOCKSS Poller Service REST API",
    author_email="lockss-support@lockss.org",
    url="https://github.com/lockss/lockss-poller-python",
    keywords=["Swagger", "LOCKSS Poller Service REST API"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    API of the LOCKSS Poller REST Service  # noqa: E501
    """
)
